### ISSUE TITLE
Using timeline theme in feed throws css compilation error 

### ISSUE THREAD

**Issue by prasannshah** [Semantic-Org/Semantic-UI-Rails-LESS#25]
It is because the theme has no globals/site.variables file inside it. As it not necessary to have the folder and the file, i suggest the changing theme.less from
`@import "@{themesFolder}/@{theme}/globals/site.variables";`
to
`@import (optional) "@{themesFolder}/@{theme}/globals/site.variables";`

**Comment by maxd** [comment]
Yes, this is a problem. `less.js` [since v.2.3.0](https://github.com/less/less.js/blob/master/CHANGELOG.md#230) support `(optional)` directive but `less` gem using v.1.7.0. Seems like not a easy to bump it to latest `less.js` version but I want to implement work-around. I will generate empty files during update version process.
