### ISSUE TITLE
Update gem with SUI 2.4.0 assets?

### ISSUE THREAD

**Issue by bborn** [Semantic-Org/Semantic-UI-Rails-LESS#51]
Wondering if you might be able to take a moment to update the gem assets to SUI 2.4.1? 

@maxd happy to help do this, but after starting to try to port the latest release into this gem, it occurred to me that you might be a lot faster.

**Comment by brendon** [comment]
Hi @bborn, just trying to at the moment but am having some trouble getting the tests to pass. I'll hopefully get something working today.

**Comment by brendon** [comment]
Hi @bborn, I'm afraid I have bad news. Due to a cascade of abandoned dependencies that `Semantic-UI-Rails_LESS` depends on on, it's non-trivial to do a version bump to `4.2`. Here's what I know:

- `Semantic-UI-Rails_LESS` 4.2.x [now defines a dependency on Less > 3.5](https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md#version-241---oct-13-2018)
- `Semantic-UI-Rails_LESS` depends on `[Less-rails](https://github.com/metaskills/less-rails)`
- `Less-rails` depends on `[less.rb](https://github.com/cowboyd/less.rb)` Not updated since early 2015! `less.rb` bundles in `Less` version 1.7 which is very old. There was an abortive attempt to update to Less 2.x (now there is 3.x) but that failed because of another abandoned dependency:
- `less.rb` depends on `[commonjs](https://github.com/cowboyd/commonjs.rb)` again not updated since 2015. This implementation of `commonjs` isn't complete and doesn't have enough functionality to compile `less.js` as it stands.

To be honest, this has caused me to look at webpacker as an alternative to getting Semantic-UI into my Rails 4.2 app. I suspect webpacker has a lot to with why these sprockets based solutions have been abandoned.

Not sure where-too from here...

**Comment by maxd** [comment]
@brendon Lol 🤣 I have found the same dependencies several years ago and made the same conclusions. It's possible to fix/replace all these dependencies but this is required a lot of time.

**Comment by bborn** [comment]
Thanks guys ... @maxd what did you end up doing instead?

**Comment by brendon** [comment]
Lol! :) Thanks @maxd. I guess if there's a real demand, people will register their interest here. Feels like flogging a dead horse though.

@bborn, take a look at Webpacker if you're using Rails 4.2+. That's what I'm doing now. There are a few guides out there.
